<h3 align="center">Assignment 3: EN4553 (Machine Vision)</h3>
<p align="center">University of Moratuwa<br>January 1, 2023</p><br>
(a) (5 points) Complete the following Python function to read the dataset as a set of arrays. (Hint: you may use the   `np.loadtxt()` function.)

In [12]:
import numpy as np
from typing import Tuple
def load_dataset( src_dir: str ) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Load the dataset as a set of numpy arrays.
    Args:
        src_dir: Directory where dataset files are stored.
    Returns:
        (x_train, y_train, x_val, y_val, x_test) tuple where each array is one dimensional.
    """
    # reading data from the files
    x_train = np.loadtxt(src_dir + "/x_train.txt")
    y_train = np.loadtxt(src_dir + "/y_train.txt")
    x_val   = np.loadtxt(src_dir + "/x_val.txt")
    y_val   = np.loadtxt(src_dir + "/y_val.txt")
    x_test  = np.loadtxt(src_dir + "/x_test.txt")
    
    # returning as a tuple
    return (x_train, y_train, x_val, y_val, x_test)

In [20]:
dataset = load_dataset("180631J")
print(dataset[0].shape[0])
print(type(dataset))
print(dataset[0])

25
<class 'tuple'>
[0.48912537 0.86703863 0.31662514 0.05414282 0.84226423 0.47318818
 0.35198499 0.75490536 0.57628842 0.97492467 0.44388158 0.0404764
 0.03644696 0.95521642 0.36810051 0.09351638 0.68300352 0.28589151
 0.15912733 0.19551489 0.68254875 0.82677867 0.16370857 0.17477055
 0.25375125]


(b) We will be fitting a linear regression model $y=\sum_{i=1}^{n} w_i x^i $ where each $w_i$ is a learnable parameter and n is
a hyperparameter. Variables x and y represent rows in `x_train.txt` and `y_train.txt`.

i. (5 points) Implement the following function to make input features for the above linear regression model.

In [41]:
def get_features(x: np.ndarray, n: int) -> np.ndarray:
    """Creates n-th degree polynomial features for the given vector x.
    Example usage:
    get_features(np.array([1.0, 2.0, 3.0]), 3) outputs
    np.array([  [ 1., 1., 1.],
                [ 2., 4., 8.],
                [ 3., 9., 27.]])
    Args:
        x: A numpy array of shape (num_examples, ) or (num_examples, 1).
        n: The degree of the polynomial features.
    Returns:
        A matrix of shape (num_examples, n) where the j-th column is equal to
        the vector x raised, elementwise, to the power j.
    """
    
    # create an array of powers 
    powers = np.arange(1, n+1)

    # reshape x to have the shape (num_examples, 1) to be compatible with np.power broadcasing
    x = x.reshape(-1, 1)

    # construct the design matrix of shape (num_examples, n)
    design_matrix = np.power(x, powers)

    # return the design matrix
    return design_matrix

In [42]:
mat = get_features(dataset[0], 3)
print(mat.shape)
print(mat)

(25, 3)
[[4.89125368e-01 2.39243625e-01 1.17020126e-01]
 [8.67038626e-01 7.51755979e-01 6.51801471e-01]
 [3.16625142e-01 1.00251481e-01 3.17421393e-02]
 [5.41428233e-02 2.93144532e-03 1.58716726e-04]
 [8.42264233e-01 7.09409039e-01 5.97509860e-01]
 [4.73188183e-01 2.23907057e-01 1.05950174e-01]
 [3.51984989e-01 1.23893433e-01 4.36086286e-02]
 [7.54905359e-01 5.69882101e-01 4.30207052e-01]
 [5.76288420e-01 3.32108343e-01 1.91390192e-01]
 [9.74924671e-01 9.50478114e-01 9.26644563e-01]
 [4.43881576e-01 1.97030854e-01 8.74583660e-02]
 [4.04764027e-02 1.63833918e-03 6.63140763e-05]
 [3.64469617e-02 1.32838102e-03 4.84154522e-05]
 [9.55216418e-01 9.12438406e-01 8.71576146e-01]
 [3.68100506e-01 1.35497982e-01 4.98768758e-02]
 [9.35163812e-02 8.74531355e-03 8.17830075e-04]
 [6.83003517e-01 4.66493804e-01 3.18616909e-01]
 [2.85891515e-01 8.17339583e-02 2.33670452e-02]
 [1.59127333e-01 2.53215081e-02 4.02934405e-03]
 [1.95514889e-01 3.82260717e-02 7.47376616e-03]
 [6.82548746e-01 4.65872791e-01 

ii. (10 points) Use the above function to complete the following implementation. (Hint: you may use the `sklearn.linear_model.LinearRegression` class.)

In [3]:
def fit_and_evaluate(
x_train: np.ndarray, y_train: np.ndarray,
x_val: np.ndarray, y_val: np.ndarray,
n: int
) -> Tuple[float, float]:
    """Fits an n-th degree polynomial and outputs train and validation MSE.
    Fits a linear regression model y = sum_{i=1}^n w_i x^i to the given train
    set and outputs the mean-squared-error (MSE) on train and validation sets.
    Args:
    x_train: Input features for the train set. Has shape (num_train, )
    y_train: Targets (labels) for the train set. Has shape (num_train, )
    x_val: Input features for the validation set. Has shape (num_val, )
    y_val: Targets (labels) for the validation set. Has shape (num_val, )
    n: The degree of the polynomial fit. See the above equation.
    Returns:
    (train_mse, val_mse), tuple of MSE on train and validation sets.
    """
    # Fit the mode  l on the train set.
    pass
    # Generate model predictions for the train set and calculate the MSE.
    y_predict_train = ...
    train_mse = mse(y_train, y_predict_train)
    # Similarly, calculate the MSE on the val set.
    val_mse = ...
    return train_mse, val_mse

(c) (5 points) Use the above function to calculate and plot train and validations MSEs against n = 1, 2, . . . , 10.
Include this graph in your answer sheet. Which n value would you pick for your final model?

(d) (5 points) Use the model selected above to make predictions on the test set. Include your predictions in a
file named `<your-index-number>_y_predict_test.txt`. For example, `180000X_y_predict_test.txt`.